#PORT
server:
  port: 8080

#BASE URL
base:
  url: http://localhost:8080

#FIREBASE
firebase:
  storage:
    bucket: virtualglamour-55401.appspot.com
    folders:
      path: product-images

#JWT
application:
  security:
    jwt:
      secret-key: e959699588321464067931aa1110b82d86cbf5a16d71f490cb8f5fa9d6dda0d8
      expiration: 7200000 #TWO HOURS
      refresh-token:
        expiration: 2419200000 #ONE MONTH

#ACTIVE PROFILE
spring:
  profiles:
    active: dev
  jpa:
    open-in-view: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: virtual.glamour.vp@gmail.com
    password: vhsyvbpxlipikfke
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
---
#DEV PROFILE
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/virtual_glamour
    password: Lakindu@MySQL
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

---
#QA PROFILE
spring:
  config:
    activate:
      on-profile: qa
  datasource:
    url: jdbc:mysql://localhost:3306/qa_db
    username: root
    password: "SQL PASSWORD"
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true

---
#PROD PROFILE
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://localhost:3306/prod_db
    username: root
    password: "SQL PASSWORD"
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
